-- Esegui questa migrazione nell'SQL Editor di Supabase.
create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  team text not null,
  player text not null
);

alter table public.goals enable row level security;
create policy "Marcatori pubblici" on public.goals for select using (true);
create policy "Solo amministratori inseriscono marcatori" on public.goals for insert
  to authenticated with check (public.is_tournament_admin());
alter publication supabase_realtime add table public.goals;
