-- Esegui questo file integralmente nell'SQL Editor di Supabase.
create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  day text not null,
  date text not null,
  home text not null,
  away text not null,
  home_score integer check (home_score >= 0),
  away_score integer check (away_score >= 0)
);

create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade
);

alter table public.matches enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_tournament_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (select 1 from public.admin_users where id = auth.uid());
$$;

revoke all on function public.is_tournament_admin() from public;
grant execute on function public.is_tournament_admin() to authenticated;

create policy "Risultati pubblici" on public.matches for select using (true);
create policy "Solo amministratori aggiornano" on public.matches for update
  to authenticated using (public.is_tournament_admin())
  with check (public.is_tournament_admin());
create policy "Solo amministratori inseriscono" on public.matches for insert
  to authenticated with check (public.is_tournament_admin());
create policy "Solo amministratori eliminano" on public.matches for delete
  to authenticated using (public.is_tournament_admin());

alter publication supabase_realtime add table public.matches;

-- DOPO aver creato l'utente amministratore in Authentication > Users, esegui:
-- insert into public.admin_users (id)
-- select id from auth.users where email = 'la-tua-email@esempio.it';
