-- Esegui questo file integralmente nell'SQL Editor di Supabase.
create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  day text not null,
  date text not null,
  home text not null,
  away text not null,
  home_score integer check (home_score >= 0),
  away_score integer check (away_score >= 0)
);

create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade
);

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  team text not null,
  player text not null
);

create table if not exists public.tournament_settings (
  id boolean primary key default true check (id),
  champion text check (champion in ('nord', 'sud', 'centro-storico', 'palazzoni'))
);

alter table public.matches enable row level security;
alter table public.admin_users enable row level security;
alter table public.goals enable row level security;
alter table public.tournament_settings enable row level security;

create or replace function public.is_tournament_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (select 1 from public.admin_users where id = auth.uid());
$$;

revoke all on function public.is_tournament_admin() from public;
grant execute on function public.is_tournament_admin() to authenticated;

create policy "Risultati pubblici" on public.matches for select using (true);
create policy "Solo amministratori aggiornano" on public.matches for update
  to authenticated using (public.is_tournament_admin())
  with check (public.is_tournament_admin());
create policy "Solo amministratori inseriscono" on public.matches for insert
  to authenticated with check (public.is_tournament_admin());
create policy "Solo amministratori eliminano" on public.matches for delete
  to authenticated using (public.is_tournament_admin());
create policy "Marcatori pubblici" on public.goals for select using (true);
create policy "Solo amministratori inseriscono marcatori" on public.goals for insert
  to authenticated with check (public.is_tournament_admin());
create policy "Solo amministratori eliminano marcatori" on public.goals for delete
  to authenticated using (public.is_tournament_admin());
create policy "Vincitore pubblico" on public.tournament_settings for select using (true);
create policy "Solo amministratori impostano il vincitore" on public.tournament_settings for insert
  to authenticated with check (public.is_tournament_admin());
create policy "Solo amministratori aggiornano il vincitore" on public.tournament_settings for update
  to authenticated using (public.is_tournament_admin())
  with check (public.is_tournament_admin());

alter publication supabase_realtime add table public.matches;
alter publication supabase_realtime add table public.goals;
alter publication supabase_realtime add table public.tournament_settings;

-- DOPO aver creato l'utente amministratore in Authentication > Users, esegui:
-- insert into public.admin_users (id)
-- select id from auth.users where email = 'la-tua-email@esempio.it';
